name: Update Tetris Live SVG

on:
  schedule:
    - cron: '0 12 * * *' # daily at 12:00 UTC
  workflow_dispatch:

jobs:
  generate-tetris-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install fs

      - name: Generate Tetris Live SVG
        run: node scripts/generate-tetris.js

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets/live-tetris.svg
          git commit -m "Update Tetris Live SVG [skip ci]" || echo "No changes"
          git push origin main
